version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db_700

    command: --default-authenticaton-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webdb
    ports:
      - "8700:3306"
    volumes:
      - db_data_700:/var/lib/mysql
    networks:
      - weblab700  
    restart: always

  phpmyadmin:
    image: phpmyadmin:lastest
    container_name: phpmyadmin_700
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 64M
    port:
       - "8701:80"
    depends_on:
      - db
    networks:
      - weblab700
    restart: always

networks:
  weblab700:
    driver: bridge

volumes:
  mysql_db_700:
    driver: local
     
